export { default as Footer } from "../components/footer/Footer.jsx"
export { default as Home } from "../components/home/Home.jsx"
export { default as Katalog } from "../components/katalog/Katalog.jsx"
export { default as Basket } from "../components/basket/Basket.jsx"
export {default as BasicModal} from "../components/modal/BasicModal.jsx"